### ISSUE TITLE
Change how sidebar and navigation menu items are ordered by using front matter instead of config

### ISSUE THREAD

**Issue by caendesilva** [hydephp/framework#169]
I recently experimented with using front matter to override sidebar labels and their order, and found it much more comfortable to work with than messing with config files.

```yaml
# index.md
---
label: Introduction
priority: 10
# hidden: true
---
```
