### ISSUE TITLE
Markdown & documentation features to add

### ISSUE THREAD

**Issue by caendesilva** [hydephp/framework#308]
- [x] #487
- [x] #484
- [x] #494
- [x] hydephp/framework#309
- [x] #310
- [x] #490
- [x] #483
- [x] Post and pre-processing hooks, can be used for filepath labels and blockquotes for example

**Comment by caendesilva** [comment]
Here's how colored blockquotes are handled in the DocsCI:

```css
blockquote.info {
    border-color: DodgerBlue;
}
blockquote.warning {
    border-color: orange;
}
blockquote.danger {
    border-color: red;
}
```
