### ISSUE TITLE
Add styles to Markdown Post/Preprocessors

### ISSUE THREAD

**Issue by caendesilva** [hydephp/framework#489]
PR https://github.com/hydephp/framework/pull/488 requires some new styles. These are what I used for testing:

```css
blockquote.info {
    border-color: DodgerBlue;
}

blockquote.warning {
    border-color: orange;
}

blockquote.danger {
    border-color: red;
}

blockquote.success {
    border-color: MediumSeaGreen;
}

:not(code)>.filepath {
    display: none;
}

pre>code>.filepath {
    position: relative;
    top: -.25rem;
    right: 0.25rem;
    float: right;
    opacity: .5;
    transition: opacity 0.25s;
}

.torchlight-enabled pre>code>.filepath {
    right: 1rem;
}

pre>code>.filepath:hover {
    opacity: 1;
}
```
